### ISSUE TITLE
Error Graphs with View of P Matrix and Dirilecht Effect

### ISSUE THREAD

**Issue by mketcha** [mketcha/SimplexMDK#3]
for a given r value:

4 graphs of mean squared error for mean approximation, m=1, n = 10; m =1, n = 100; m= 100, n =10; m =100, n =100

1 example of the P matrix 

1 plot showing point spread of Dirilecht latent space

**Comment by jovo** [comment]
perfect

On Friday, February 13, 2015, mketcha notifications@github.com wrote:

>  for a given r value:
> 
> 4 graphs of mean squared error for mean approximation, m=1, n = 10; m =1,
> n = 100; m= 100, n =10; m =100, n =100
> 
> 1 example of the P matrix
> 
> 1 plot showing point spread of Dirilecht latent space
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mketcha/SimplexMDK/issues/3.

## 

the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing
, jovo.me, my calendar
https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
